PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# Idiomes

INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/Language/Catalan> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#Language> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/Language/Spanish> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#Language> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/Language/English> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#Language> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/Language/French> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#Language> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/Language/Arabic> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#Language> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/Language/German> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#Language> }


# KingArtWork individuals

INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/KindArtWork/Dance> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#KindArtWork> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/KindArtWork/Installation> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#KindArtWork> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/KindArtWork/Performance> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#KindArtWork> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/KindArtWork/Photo> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#KindArtWork> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/KindArtWork/Picture> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#KindArtWork> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/KindArtWork/Requiem> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#KindArtWork> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/KindArtWork/Sculpture> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#KindArtWork> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/KindArtWork/Sonata> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#KindArtWork> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/KindArtWork/Videoart> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#KindArtWork> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/KindArtWork/Graphic> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#KindArtWork> }

# Material individuals

INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/Material/Gold> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#Material> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/Material/Iron> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#Material> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/Material/Marble> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#Material> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/Material/Pastle> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#Material> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/Material/Stone> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#Material> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/Material/Tempera> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#Material> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/Material/Titanium> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#Material> }
INSERT INTO GRAPH <http://localhost:8890/ACData> { <http://www.artscombinatories.cat/objects/Material/Wood> rdf:type <http://www.semanticweb.org/ontologies/2011/4/Ontology1304926436539.owl#Material> }